language: node_js

node_js:
  - "8"

matrix:
  include:
    - node_js: "8"
      env: ESLINT=true

cache:
  yarn: true
  directories:
    - node_modules

script:
  - if [ "$ESLINT" == true ]; then yarn lint;
    else yarn test; fi
