version: "3"
services:
  db:
    image: "mongo:${MONGO_VER}"
    restart: unless-stopped
    volumes:
      - ./storage/configdb:/data/configdb
      - ./storage/db:/data/db
  redis:
    image: "redis:${REDIS_VER}-alpine"
    restart: unless-stopped
    volumes:
      - ./storage/cache:/data
  bot:
    image: "archomeda/kormir-discord-bot:${BOT_VER}"
    command: node server.js
    restart: unless-stopped
    volumes:
      - ./config:/bot/config
    links:
      - db
      - redis
    environment:
      MONGODB: mongodb://db/kormir-discord-bot
      REDIS: redis
