module.exports = {
    EMBED_TITLE_CHARACTER_LENGTH: 256,
    EMBED_DESCRIPTION_CHARACTER_LENGTH: 2048,
    EMBED_FIELDS_LENGTH: 25,
    EMBED_FIELD_NAME_CHARACTER_LENGTH: 256,
    EMBED_FIELD_VALUE_CHARACTER_LENGTH: 1024,
    EMBED_FOOTER_TEXT_CHARACTER_LENGTH: 2048,
    EMBED_AUTHOR_NAME_CHARACTER_LENGTH: 256,
    EMBED_CHARACTER_LENGTH: 6000,
    MESSAGE_CAHRACTER_LENGTH: 2000
};
